title: Learning Rust - Part 1
author: Sébastien Dorgan
email: sebastien.dorgan@gmail.com
description: Building a portable Rust development environment with code-server and docker 
# url: "https://do4tech.github.io/01-Learn-Rust/" 

#remote_theme: yous/whiteglass

